; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp12f]
platform = espressif8266
framework = arduino
board = esp12e
monitor_speed = 115200
monitor_filters = esp8266_exception_decoder
upload_resetmethod = nodemcu
board_build.filesystem = littlefs
build_src_filter = +<*> -<esp12f_scan/>
lib_deps =
    paulstoffregen/OneWire
    milesburton/DallasTemperature
    bblanchon/ArduinoJson@^7

[env:esp12f_scan]
platform = espressif8266
framework = arduino
board = esp12e
monitor_speed = 115200
upload_resetmethod = nodemcu
build_src_filter = -<*> +<esp12f_scan/>
lib_deps =
    paulstoffregen/OneWire
    milesburton/DallasTemperature

[env:native]
platform = native
test_build_src = no
lib_deps = bblanchon/ArduinoJson@^7
test_filter = test_config_parse
